import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Recluto",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<div className="flex h-screen">
					<Sidebar />
					<div className="w-3/4">{children}</div>
				</div>
			</body>
		</html>
	);
}
